### ISSUE TITLE
Summary fails to display if no masscan file exists

### ISSUE THREAD

**Issue by fsrob** [TDSSEC/AIO-Enum#4]
Should check for the existence of the file before trying to use it

**Comment by TDSSEC** [comment]
Added an if statement in the summary to check if the masscan file exists.
If it does, perform masscan search. If not, only do nmap searches.

`for ip in $(cat "$OUTPUTDIR/alive.ip"); do
	echo -e $ip > "$OUTPUTDIR/open-ports/$ip.txt"
	if [ -f "$MASSCAN_FILE" ]; then #if masscan was executed, check both masscan and nmap
            awk \/$ip\/ "$OUTPUTDIR/masscan/scans/masscan.gnmap" | egrep -o '*[0-9]*/open/*[tcp/udp]*/' | sort | uniq | awk -F '/' '{print $1"/"$3}' >> "$OUTPUTDIR/tempports.tmp"
	    awk \/$ip\/ "$OUTPUTDIR/nmap/scans/portscan.gnmap" | egrep -o '*[0-9]*/open/*[tcp/udp]*/' | sort | uniq | awk -F '/' '{print $1"/"$3}' >> "$OUTPUTDIR/tempports.tmp"
	    cat "$OUTPUTDIR/tempports.tmp" | sort -u >> "$OUTPUTDIR/open-ports/$ip.txt"
	    rm -f "$OUTPUTDIR/tempports.tmp"
	else #just check nmap files
	    awk \/$ip\/ "$OUTPUTDIR/nmap/scans/portscan.gnmap" | egrep -o '*[0-9]*/open/*[tcp/udp]*/' | sort | uniq | awk -F '/' '{print $1"/"$3}' >> "$OUTPUTDIR/tempports.tmp"
            cat "$OUTPUTDIR/tempports.tmp" | sort -u >> "$OUTPUTDIR/open-ports/$ip.txt"
            rm -f "$OUTPUTDIR/tempports.tmp"
	fi`
