### ISSUE TITLE
Dependency and default interface issue (Masscan)

### ISSUE THREAD

**Issue by fbusr** [TDSSEC/AIO-Enum#7]
![20220228a](https://user-images.githubusercontent.com/98055920/156033515-ba4b7b1c-c47e-49d6-89f9-5781cdf559f7.png)

Script ran using default option:
`sudo /opt/AIO-Enum/aio-enum.sh -3`

**Comment by jthorpe6** [comment]
Hey @fbusr could you try with the `--masscan-interface` option and let us know if this resolves your issue?

**Comment by fbusr** [comment]
Hello @jthorpe6, please see below screenshot with the `--masscan-interface eth0` parameter included.
![20220324a](https://user-images.githubusercontent.com/98055920/159954017-196bb60d-349d-4d6b-80c4-388e72e3b9ff.png)

**Comment by jthorpe6** [comment]
Thanks @fbusr. So that's working as expected now ? Can we close this issue?

**Comment by fbusr** [comment]
Hello @jthorpe6, I don't see any issues with running the tool due to the errors. I'll go ahead and close this out.
