### ISSUE TITLE
Parsing error for 'xml-to-csv.xsl'

### ISSUE THREAD

**Issue by fbusr** [TDSSEC/AIO-Enum#8]
![20220228b](https://user-images.githubusercontent.com/98055920/156033834-94b00828-10b9-44ef-8a3a-aaf6441670c1.png)

Default script option ran with:
`sudo /opt/AIO-Enum/aio-enum.sh -3`

**Comment by jthorpe6** [comment]
Thanks @fbusr. Could you provide the `.xml` files so I can try reproduce this error?

**Comment by fbusr** [comment]
Hello @jthorpe6, the output from the above command seems to yield multiple xml files. Would you like all the xml files?

**Comment by fbusr** [comment]
![20220324e](https://user-images.githubusercontent.com/98055920/160156125-19d9c6bc-cc2d-44ed-a218-580b7b36f500.png)
Perhaps this is a related error, but the tool will hang when it attempts to parse the xml files to html.

**Comment by jthorpe6** [comment]
Yep, I need the `.xml` [files](https://github.com/TDSSEC/AIO-Enum/blob/a84043313c10540bdb0bfe2f0f8438ad66ede0a9/parsers.sh#L51) to try replicate the issue your having.
