### ISSUE TITLE
Inaccurate 'discovered_ports.txt' file

### ISSUE THREAD

**Issue by fbusr** [TDSSEC/AIO-Enum#9]
![20220228c](https://user-images.githubusercontent.com/98055920/156034717-c0bbe68d-3da8-41c0-8eff-354306b7b23b.png)

Script ran with default option:
`sudo /opt/AIO-Enum/aio-enum.sh -3`

**Comment by jthorpe6** [comment]
hey @fbusr the `open-ports` directory is used to give a breakdown per port and per IP. This is expected behaviour.
